# Deployment
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mi-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mi-aplicacion
  template:
    metadata:
      labels:
        app: mi-aplicacion
    spec:
      containers:
        - name: mi-contenedor
          image: RegistroRedes.azurecr.io/mi-aplicacion:latest
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: mi-registro-secret
      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Exists"

# Service
---
apiVersion: v1
kind: Service
metadata:
  name: mi-servicio
  namespace: default
spec:
  selector:
    app: mi-aplicacion
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP